# action.yml
name: 'Akamai Purge'
description: 'Purge content on the Akamai network from your Github workflow'
branding:
  icon: 'cloud-off'
  color: 'gray-dark'
inputs:
  command:
    description: 'Purge command (delete, invalidate)'
    required: true
  type:
    description: 'Purge type (tags, cpcode)'
    required: true
    default: 'tags'
  ref:
    description: 'Reference'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.ref }}
